# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
                ('slots', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='TT',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sch.Schedule'),
        ),
    ]
