# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_auto_20171008_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=4)),
                ('year', models.IntegerField()),
                ('TT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sch.Schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='Tid',
            field=models.CharField(default='', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
