# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('sch', '0003_auto_20171009_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.AddField(
            model_name='batch',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='person',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.Batch'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='stream',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slots',
            field=models.CharField(default='', max_length=8),
        ),
    ]
