# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_auto_20171017_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
                ('value', models.CharField(default=b'', max_length=4)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.Dicty')),
            ],
        ),
    ]
