# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0005_dicty_keyval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sch.Dicty'),
        ),
    ]
