# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0007_auto_20171023_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='dic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.KeyVal'),
        ),
        migrations.AddField(
            model_name='person',
            name='dic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.KeyVal'),
        ),
    ]
